# "What's your name?"
# "Hello XY, I am your phone book."
# "How old are you?"
# - "You are so young! Life is ahead of you!"
# - "That's a nice age!"
# - "You must be very wise!"
# - "That doesn't seem to be an integer."
